apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvcviewer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davidspek/kubeflow
    targetRevision: pvc-viewer-controller
    path: components/pvcviewer-controller/config/overlays/kubeflow
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
