apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: nnVafuNPngvespw17w4NcDR0SAGb7Fey/1FfO7ZQnnaqW/8BBbizfCz0lDvbr/0n81JfDExHWasZJqt345ZVlhkW2P7Lb6MiXhNE/7Akr7qJ04amcyL7YQldVnq/JkLAH5Lu6HYhNAv0cweYNqHJZinaUHVWKrJPGICwFZYPDR4=
